### ISSUE TITLE
Error: Class [Env] does not exist.

### ISSUE THREAD

**Issue by ghost** [czim/laravel-json-context-logging#1]
Greetings,
the following line in your default Config Throws an error for me. 

https://github.com/czim/laravel-json-context-logging/blob/c90260b1c19cbcdecebbe882cd3bab0b60030b29/config/json-context-logging.php#L42

Localy I sollved it by switching it to `env('APP_NAME')` 

Composer Require for Ref: 
![image](https://user-images.githubusercontent.com/57394581/90489267-58f61b80-e13d-11ea-9b7c-a305092ee29a.png)

**Comment by czim** [comment]
I've changed the config to use `env()` directly, as you indicated, in the newest version. 👍
